<strong>Module:</strong>        CtDisplay &raquo;
<strong>Controller:</strong>    CtDisplay &raquo;
<strong>Action:</strong>        index

<div style="margin-top:16px">
<h2>Request information</h2>
<pre><?php echo $metadata ?></pre>
<h2>Execution trace</h2>
<pre>
<?php foreach($frames as $frame): ?>
<?php
    $prefix = '';
    $suffix = '';
    if (strpos($frame, '***ERROR***') !== false) {
        $prefix = '<font style="color:red">';
        $suffix = '</font>';
    } elseif(strpos($frame, '***WARNING***') !== false) {
        $prefix = '<font style="color:gold">';
        $suffix = '</font>';
    }
?>
<?php echo "{$prefix}{$frame}{$suffix}", PHP_EOL ?>
<?php endforeach ?>
</pre>
<h2>Function calls</h2>
<table id="callstable" style="width: 400px; margin: 16px"></table>

</div>

<?php 

//$calls = array('responseData' => $calls);

?>

<script type="text/javascript">
window.addEvent('load', function(){
	var initData = <?php echo json_encode($calls) ?>;
    var callscmu = [
			{
				'title': _t('Name'),
				'dataIndex': 'function',
				'parser': zGrid2.prototype.string,
				'width': '100%',
				'sortable': true,
				'sortBy': 'function'
			},
			{
				'title': _t('#'),
				'dataIndex': 'count',
				'parser': zGrid2.prototype.string,
				'width': '30px',
				'sortable': true,
				'sortBy': 'count'
			}
    	];

        <?php
								$options = array (
										'idColumn' => 'id',
                                        'rowExpand' => false,
                                        'description' => false,
								);
								?>
        callsgrid = <?php echo $this->zGrid2('callstable', 'callscmu', $options); ?>
        callsgrid.setData(initData);    
});

</script>